name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
    - "v*"

  build:
    runs-on: ${{ matrix.os }}
    permissions:
        contents: write
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [22]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build Electron app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for private repository access
      run: npm run build --verbose

    - name: Debug build output
      run: ls -R dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: |
          dist/mindcomplete-*.exe
          dist/mindcomplete-*.AppImage
          CHANGELOG.md

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifact
        
    - name: Display structure of downloaded files
      run: ls -R artifact

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifact/ubuntu-latest/dist/mindcomplete-*.AppImage
          artifact/windows-latest/dist/mindcomplete-*.exe
        body_path:  artifact/windows-latest/CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}