name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [22]
        arch: [x64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        shell: bash
        run: |
          for i in 1 2 3; do
            npm install && break
            sleep 10
          done

      - name: Build Electron app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build -- --${{ matrix.arch }}

      - name: List build output
        run: ls -R dist

      - name: Compress build output linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p packaged
          cd dist
          zip -r ../packaged/mindcomplete-linux-${{ matrix.arch }}-${{ github.ref_name }}.zip mindcomplete-*.AppImage

      - name: Compress build output windows
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p packaged
          cd dist
          powershell -Command "Compress-Archive -Path 'mindcomplete-*.exe' -DestinationPath '../packaged/mindcomplete-win32-${{ matrix.arch }}-${{ github.ref_name }}-install.zip'"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: |
            packaged/mindcomplete-*.zip
            CHANGELOG.md

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifact

      - name: Display structure of downloaded files
        run: ls -R artifact

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifact/ubuntu-latest-x64/packaged/mindcomplete-*.zip
            artifact/ubuntu-latest-arm64/packaged/mindcomplete-*.zip
            artifact/windows-latest-x64/packaged/mindcomplete-*.zip
            artifact/windows-latest-arm64/packaged/mindcomplete-*.zip
          body_path: artifact/windows-latest-x64/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}