name: Create Changelog

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Install standard-version
      run: npm install --save-dev standard-version conventional-changelog-conventionalcommits

    - name: Get latest commit user and email
      run: |
        COMMIT_USER=$(git log -1 --pretty=format:'%an')
        COMMIT_EMAIL=$(git log -1 --pretty=format:'%ae')
        echo "Latest commit user: $COMMIT_USER"
        echo "Latest commit email: $COMMIT_EMAIL"
        git config --local user.email $COMMIT_EMAIL
        git config --local user.name  $COMMIT_USER

    - name: Generate changelog and bump version
      run: |
        npx standard-version
        git push --follow-tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}